ingress:
  enabled: true
  nginxInc: true
  annotations:
      nginx.ingress.kubernetes.io/client-body-buffer-size: 10M
      nginx.ingress.kubernetes.io/proxy-body-size: 10M
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: "mysql-monitoring.prod-cluster.internal.locthp.com"
      external-dns.alpha.kubernetes.io/target: "172.16.1.199"
  community:
    annotations: {}
  ingressClassName: "nginx"

  ## Ingress resource hostnames and path mappings
  hosts:
    - host: mysql-monitoring.prod-cluster.internal.locthp.com
      paths: ["/"]
  pathType: Prefix
  tls:
    - secretName: mysql-monitoring-cert
      hosts:
        - mysql-monitoring.prod-cluster.internal.locthp.com

storage:
  ## @param storage.name name of PVC
  name: pmm-storage
  storageClassName: ""
  size: 10Gi
  dataSource: {}
  selector: {}
