version: '3.8'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
    volumes:
      - ./db-creation.sql:/docker-entrypoint-initdb.d/script.sql
#  flask:
#    image: flask_service:dev
#    ports:
#      - "5001:5000"
#    environment:
#      - MYSQL_HOST=mysql
#      - WS_HOST=172.16.2.252
#  socket:
#    image: socket_service:dev
#    ports:
#      - "8000:8000"
networks:
  chat_app:
    name: chat_app
    driver: bridge