apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opentelemetry-ebpf-instrumentation
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.8.0
    releaseName: obi
    namespace: observability
    valuesFile: values.yaml
