apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: homepage-secrets
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
stringData:
    HOMEPAGE_VAR_OPNSENSE_USERNAME: ENC[AES256_GCM,data:IlZ5vSkrb5EqmXB60RiDwMQ0ov1QKGjokOjlYHqoyCXJDYvMIpkWeGCm7rh50AQHr+gOIDCRx0e0LLctW3Vhz0preKzHYphtfZ0CXo62ufU=,iv:JIgq26Sf1IBQCOoGbS0MfszBHeMOxZWFbNyAEGsg+mk=,tag:iI/qnoEhphhhVR1tGeqXhg==,type:str]
    HOMEPAGE_VAR_OPNSENSE_PASSWORD: ENC[AES256_GCM,data:2zeURzTH/LnyJ1vpeO9/K0F3/sjFC95h2nCob9fDbp23N/8cSO0KZbPdPlIYF2KWtbCA8/KUypwWkYfmfRJB2EE/qvHk+ZjmTgdGVJn8d/Y=,iv:y0aNjSV83c95d/s67cHUiYGmVVXkcwOx6Vsnc7ZDzPg=,tag:8MpOi9Dp9J1zKi7ltQduLg==,type:str]
    HOMEPAGE_VAR_PIHOLE_MASTER_KEY: ENC[AES256_GCM,data:NrErGyMyRlNF0AO7wiqNU0vTeaKMNX64q5FQVBh5alFuhbDq3wFe8jE+sFczcxGo49RlXrayI8BQef+s9Ehjug==,iv:optqLI9wd+sTUKTmGQCoCcvJIPeMV3uRhYWRacgXEuk=,tag:AUqsLFrhBHPQ7TYtXIfXyA==,type:str]
    HOMEPAGE_VAR_PIHOLE_SLAVE_KEY: ENC[AES256_GCM,data:qPUt8EizUFOIo5ws2yRYc6ENLn493F3KF6zuXpn9vtg9ILgQyS37pb1TDEQXOBtOqztY95EqZ4Nrv8dK8H/rmA==,iv:QHQ9oV+2IACMDtCo7lKvvVczmlK4083OHlRoN3oms9A=,tag:YVaG3iT97MGSDJxD2Diiyw==,type:str]
    HOMEPAGE_VAR_PROXMOX_USERNAME: ENC[AES256_GCM,data:b6sI1OUrd1x0taSx/qDEPQ==,iv:dle269ksAAlqg+7UwXf+lkyHbDbkZlP0HUfIx4pF37U=,tag:ypEtTWtDelMGH34X6dIGSg==,type:str]
    HOMEPAGE_VAR_PROXMOX_INTELNUC01_PASSWORD: ENC[AES256_GCM,data:ofd6rthIj83qqd+/tqjDqvO1umx2mtqxAFikoaCjahIvqLXN,iv:+rT9Fx4BLVv8fepRnz13FZyrwukkhDF88GsR2mW7CwI=,tag:yTR7K+oJaPiIiIN6PeOkJA==,type:str]
    HOMEPAGE_VAR_PROXMOX_HP02_PASSWORD: ENC[AES256_GCM,data:GPdtsnL2Aiw2hvEZxbDGDhaT70Mh09/I74igtrA+Wz03xEDJ,iv:brohIajzSrs16VCvpZLpEyrw05iKZAqL98qE1JKUNlw=,tag:iWDq69yxK1m6lrubua103A==,type:str]
    HOMEPAGE_VAR_PROXMOX_DELL03_PASSWORD: ENC[AES256_GCM,data:9bF2yXdGlOIt3AuRQf4Znuui3UoQ0U+R3xDFop37Sr0JQ/ca,iv:gJZXAZM5u8YZbuiPXoRPvGk/BqgEHPDJp7ML2suEFV8=,tag:QFqLoqjXrJ1ojJ+tlEjZbw==,type:str]
    HOMEPAGE_VAR_PROXMOX_GEEKOMDEV_PASSWORD: ENC[AES256_GCM,data:Z00b/M0ja3Q294pdsWHrxkgytWCdKDWRypcnZJ2p5hTrYRlY,iv:N+AFP+/JjwZki8MMv72c+E65/DordmJpWMq4y2/Gx38=,tag:xlEU/WpqBQ6lR5TiSMmTWw==,type:str]
    HOMEPAGE_VAR_GRAFANA_USERNAME: ENC[AES256_GCM,data:M7kjQw8=,iv:5+zDuKHoUvdCJuEKAqfcGhbWuNa2ftNqt6Wx2n2t+8g=,tag:ksDElarc3Z+9/N7FOp7J9A==,type:str]
    HOMEPAGE_VAR_GRAFANA_PASSWORD: ENC[AES256_GCM,data:uC5v9XvlqJDxeQ==,iv:mRTsavuodymshyYksIk1QUTQwY0choq+KjGv5rNYRGQ=,tag:ukmnhlPNouoC0papjeHKpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MVRqM3hQbnFtUGorL2Ey
            QmlRamhaUEVDQmE0K3llL1lnVG5JakhESGdjClM1a0hCME5xMnJnaEhMS0lYaENs
            M1I2Zis5NEsvSHZiNHlOalhjbzNOTjgKLS0tIHNPbzZkUks5dVlJc3JicVJkc29H
            UlhTWEJFREJkbW1zSGFsbGZNQVpNZjgKwcmA9YTpte654gMIofTdoj0pwDtQCjRV
            JtNQJMscVKjb5x3fT6GQlxVUYZzgE95Zsuk9d/p0sfsae1vSYXrTYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T04:34:19Z"
    mac: ENC[AES256_GCM,data:tvcWu0+LhIEs6VRA+Vo7zhIRgnzMaVHzuYiRmR0cW4e1jz6n19ZRAb9RbW41K/1gSc7JynrwgqF+3AB8ps0fWXpc32YAx+6Dchsustu0GIpOyuBlmrdI3an5BlcPUUQJLcjupLRHXP2ex29AMd10dJzfC3mRUToNEh5nTjcMrdM=,iv:IOR+oLtdJ4xIisqoHV00hD97mA6HqGxxIbxkmBcL9uM=,tag:7sxE5gS9/7cnLgjwunfoyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
