apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated-lb
  namespace: monitoring
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 9090
      targetPort: http-web
  selector:
    app.kubernetes.io/name: prometheus
  type: LoadBalancer
