[build]
  base = "docs/"
  publish = "public"
  command = "hugo --gc -b $DEPLOY_PRIME_URL/nginx-ingress-controller"

[context.development]
  command = "make all-dev"

[context.staging]
  command = "make all-staging"

[context.production]
  command = "make all"

[context.deploy-preview]
  command = "make deploy-preview"

[context.branch-deploy]
  command = "make deploy-preview"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-ingress-controller/"
  status = 301
  force = true


[[redirects]]
  from = "/nginx-ingress-controller/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-ingress-controller/*"
  to = "/nginx-ingress-controller/404.html"
  status = 404
