auth_enabled: false

server:
  http_listen_port: 3100
  http_tls_config: &tls_server_config
    cert_file: /opt/loki/mycertificate.crt
    key_file: /opt/loki/mycertificate.key

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h