apiVersion: v1
kind: Secret
metadata:
    name: ksops-smoke-test
    namespace: default
    labels:
        app.kubernetes.io/name: ksops-smoke-test
        app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
    hello: ENC[AES256_GCM,data:8bhcPPLUcJ+BSy8=,iv:XRDaxnO8nshs1U+IRe4YwnaiF0yZ1PR3qdZemDTb8y8=,tag:L5FtUqVrqj8IORgcURfi5A==,type:str]
    note: ENC[AES256_GCM,data:ceqoDx71wPssKps2GUFEUPFxF7XbFI/1mFwEjaAT9xwWXjmiO5gEYsCwGYBNzufQj0OXJxMAno5vsK48mPAGH6tvTg==,iv:XMwRNa3ubFWXLzeuXKVPqONxC5/o3ZSfl5dd3TXmiOg=,tag:zbi9CMf6qnrFVf5KMgpnYA==,type:str]
    timestamp: ENC[AES256_GCM,data:gwfdQ+ryRwsBAA==,iv:L5YKBHeS6Eq7e1koaCg/vlQhxfTQGH4/cR0zWSJIqx8=,tag:JzcCA44Vvu/NVoUdrxN9QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPc1h2TW1obHhBTkZSbVpU
            RjllWkg4SS9ZZmV5QnVFc3ltUmhNeFJJemt3Clc3OFdiRlYvS1lXdkowVUNMQW9V
            U2ZLQ3o5WUNOY2Nmay9iQTFvak5Ca3MKLS0tIEgrTnFIUGxLaDdydmJWbEhGSERx
            OExHSTBZRTNmenQ2Ri9sS3c0dXZUbDgKY/9u3CfZ+hw+e6Iw56VcvVfVl2UIMGAw
            CSm37Yo7yKihl9glMsEuTvwrgpPTArmz3cvTJmMtxMjPO/JJUMRQFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T03:28:47Z"
    mac: ENC[AES256_GCM,data:/mf3bi74Mpoxx0Q4tDQRO3W27jpM+6z9deIhKtzBStXE9FiSedc8Xu6fxmhIdzTkSPDrNbTK9mk/Z69anPnMJH6xWd7AZzvwppsfhVSAhr3CIT+qMbhcAaTLulhseEo01j+goV6huPEwI2o82/40opApqm9dPxsg5rjIiWnk0Z4=,iv:1+WVlAoOQm1HfHGrPrUqW4xQADbN3shDGuvb0Ltrx4Y=,tag:gVX9SNzljagRNO298UPXJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
