// Code generated by lister-gen. DO NOT EDIT.

package v1

// DNSEndpointListerExpansion allows custom methods to be added to
// DNSEndpointLister.
type DNSEndpointListerExpansion interface{}

// DNSEndpointNamespaceListerExpansion allows custom methods to be added to
// DNSEndpointNamespaceLister.
type DNSEndpointNamespaceListerExpansion interface{}
