apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: snapshot-controller
    repo: https://piraeus.io/helm-charts/
    version: 5.0.3
    releaseName: snapshot-controller
    namespace: kube-system
    valuesFile: values.yaml
    includeCRDs: true
