global:
  scrape_interval: 10s
rule_files:
  - ./alert_rules/config.yml
  - ./recording_rules/config.yml
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 172.16.1.244:9100


