global:
  scrape_interval: 15s
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets: [ 'alertmgr:9093' ]
rule_files:
  - ./alert_rules/config.yml
  - ./recording_rules/config.yml

scrape_configs:
  - job_name: 'local-prometheus'
    static_configs:
     - targets: [localhost:9090]

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - ./targets/*.yml

  - job_name: 'federate'  
    scrape_interval: 15s
 
    honor_labels: true 
    metrics_path: '/federate'
    scheme: https
    params:
      'match[]':
          - '{job="node-exporter"}'
          - '{job="ingress-nginx-controller-metrics"}'
    #params:
    #  'match[]':
    #    - '{__name__=~".+"}'
    static_configs:
      - targets: ['prometheus.prod-cluster.internal.locthp.com']

  - job_name: 'bind-exporter'
    static_configs:
     - targets:
        - 172.16.1.2:9119
        - 172.16.1.3:9119

