global:
  scrape_interval: 15s
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets: [ 'alertmgr:9093' ]
rule_files:
  - ./alert_rules/config.yml
  - ./recording_rules/config.yml
scrape_configs:
  - job_name: 'local-prometheus'
    static_configs:
     - targets: [localhost:9090]

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - ./targets/*.yml

  - job_name: 'federate'  
    scrape_interval: 45s
    scrape_timeout: 30s
 
    honor_labels: true 
    metrics_path: '/federate'
    scheme: https
    params:
      'match[]':
          - '{job="node-exporter"}'
    static_configs:
      - targets: ['prometheus.internal.locthp.com']


