global:
  scrape_interval: 10s
#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets: [ 'alertmgr:9093' ]
rule_files:
  - ./alert_rules/config.yml
  - ./recording_rules/config.yml
scrape_configs:
  - job_name: 'local-prometheus'
    static_configs:
     - targets: [localhost:9090]

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
        - ./targets/*.yml


