apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: LocTruong's Homepage
    layout:
      Networking Group:
        style: row
        columns: 3
      Infrastructure:
        style: row
        columns: 3
    providers:
      longhorn:
       url: https://longhorn.internal.locthp.com

  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Networking Group:
        - Firewall:
            icon: opnsense.png
            href: http://172.16.1.1/
            description: Opensese Firewall
            ping: 172.16.1.1
            widget:
               type: opnsense
               url: http://172.16.1.1
               username: "ZZ6Z+MKerzSQbSMyBY8dS4wjdupIDhX1AQSyz1gccKSpiCtYsSM/4VixGklgJbuJy+zdUHOzJeiOV3FT"
               password: "MLbHiodPuW4iFvF50OjEEaWTJcutD5XAIp3PrSe+/AYgQuRJRPrUlChe/Rhsapnj1cA3iUlfDHLBa45l"
        - Pihole Master:
            icon: pi-hole.png
            href: http://172.16.1.5/admin
            description: Pihole Resolver
            ping: 172.16.1.5
            widget:
               type: pihole
               url: http://172.16.1.5/admin/api.php?summaryRaw&auth=
               key: "1a8c0be3938728373100d2a3ae8d3c57ebf37f4087fd4bc51c75ab7c2ed3fdad"

        - Pihole Slave:
            icon: pi-hole.png
            href: http://172.16.1.6/admin
            description: Pihole Resolver
            ping: 172.16.1.6
            widget:
               type: pihole
               url: http://172.16.1.6/admin/api.php?summaryRaw&auth=
               key: "1a8c0be3938728373100d2a3ae8d3c57ebf37f4087fd4bc51c75ab7c2ed3fdad"

    - Infrastructure:
        - Proxmox-intelnuc-01:
            href: https://172.16.1.250:8006/
            description: This node's being temporarily not used
            icon: proxmox.png
            ping: 172.16.1.250
        - Proxmox-hp-02:
            href: https://172.16.1.251:8006/
            description: PVE virtualization platform
            icon: proxmox.png
            ping: 172.16.1.251
            widget:
              type: proxmox
              url: https://172.16.1.251:8006
              username: "api@pam!homepage"
              password: "5c85c1d4-6169-49e3-a5f8-499df7c8ccab"
        - Proxmox-dell-03:
            href: https://172.16.1.252:8006/
            icon: proxmox.png
            description: PVE virtualization platform
            ping: 172.16.1.252
            widget:
              type: proxmox
              url: https://172.16.1.252:8006
              username: "api@pam!homepage"
              password: "73caa800-d914-41e8-af2a-7c03fd4732c6"

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: false
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
    # - longhorn:
    #     # Show the expanded view
    #     expanded: true
    #     # Shows a node representing the aggregate values
    #     total: true
    #     # Shows the node names as labels
    #     labels: true
    #     # Show the nodes
    #     nodes: true

    - search:
        provider: google
        target: _blank
    - datetime:
      text_size: xl
      format:
        timeStyle: short
  docker.yaml: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  # - apiGroups:
  #     - traefik.containo.us
  #   resources:
  #     - ingressroutes
  #   verbs:
  #     - get
  #     - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    gethomepage.dev/description: Dynamically Detected Homepage
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/name: Homepage
    nginx.org/redirect-to-https: 'True'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - homepage.internal.locthp.com
    secretName: homepage-certificate
  rules:
    - host: "homepage.internal.locthp.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
