- name: Generate join token
  shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd
  when: inventory_hostname == groups['k8s-masters'][0]
  
- name: Store join command
  set_fact:
    kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
  when: kubeadm_join_cmd.stdout is defined

- name: Generate Cert Key
  shell: kubeadm init phase upload-certs --upload-certs
  register: cert_key
  when: inventory_hostname == groups['k8s-masters'][0]

- name: Store Cert Key
  set_fact:
    cert_key: "{{ cert_key.stdout_lines[2] }}"
  when: cert_key.stdout_lines[2] is defined


- name: Run kubeadm join
  shell: "{{ hostvars[groups['k8s-masters'][0]]['kubeadm_join'] }} --control-plane --certificate-key {{ hostvars[groups['k8s-masters'][0]]['cert_key'] }}"
  when: inventory_hostname != groups['k8s-masters'][0]