- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Rescan SSH key
    #description: "Rescan the keys for newly created Hosts to avoid overlapping if they exist already"
    shell:
      cmd: "ssh-keygen -R {{ item }} && ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
    with_items: "{{ groups['all'] }}"

- hosts: all
  remote_user: locthp
  become: true
  tasks:
  - name: Update the Ubuntu servers to be latest
    apt:
      update_cache: true
      force_apt_get: true
      upgrade: "yes"
    when: ansible_distribution == "Ubuntu"
    async: 7200
    poll: 5
    register: update_result
  - name: Install docker
    block:
      - name: Install necessary components
        apt:
          name:
            - ca-certificates
            - curl
          state: present
      - name: Ensure /etc/apt/keyrings directory exists
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'
      - name: Download Docker GPG key to /etc/apt/keyrings/docker.asc
        ansible.builtin.get_url:
          url: https://download.docker.com/linux/ubuntu/gpg
          dest: /etc/apt/keyrings/docker.asc
          mode: '0644'
          force: yes
      # - name: Add Docker repository
      #   lineinfile:
      #     path: /etc/apt/sources.list.d/docker.list
      #     line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      #     create: yes
      - name: Add Docker Repo
        ansible.builtin.apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
          filename: docker
          state: present
          update_cache: true
      - name: Install Docker components
        apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          state: present
      - name: Enable Docker to kick off at boot
        ansible.builtin.systemd_service:
          name: docker
          enabled: true
      - name: Add Remote User to Docker group
        user:
          name: "{{ ansible_user }}"
          group: docker
          append: yes
      - name: Copy Secrets to Server
        ansible.builtin.copy:
          src: ../../configuration/secret-env-exporting.sh
          dest: ~/.secret-env-exporting.sh
          mode: 0744
        become: false


      




