apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
  labels:
    app: tcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
      - name: tcp-server
        image: locthp/tcp-server:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 65432
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-service
spec:
  type: LoadBalancer
  ports:
    - port: 65432
      targetPort: 65432
      protocol: TCP
  selector:
    app: tcp-server