apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: devops-tools
  annotations:
    nginx.org/ssl-redirect: 'True'
    # nginx.org/keepalive: "32"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/proxy-connect-timeout: "90"
    nginx.org/proxy-read-timeout: "90"
    nginx.org/proxy-send-timeout: "90"
    nginx.org/proxy-buffering: "False"
    nginx.org/client-max-body-size: "10m"
    nginx.org/location-snippets: |
      proxy_redirect https://jenkins.internal.locthp.com/manage/ https://jenkins.locthp.com/manage/;
    # nginx.org/server-snippets: |
    #   location ~ "^/static/[0-9a-fA-F]{8}\/(.*)$" {
    #     # rewrite all static files into requests to the root
    #     # E.g /static/12345678/css/something.css will become /css/something.css
    #     rewrite "^/static/[0-9a-fA-F]{8}\/(.*)" /$1 last;
    #   }
    #   ignore_invalid_headers off;
    #   location /userContent {
    #   # have nginx handle all the static requests to userContent folder
    #   # note : This is the $JENKINS_HOME dir
    #       root /var/lib/jenkins/;
    #       if (!-f $request_filename){
    #           # this file does not exist, might be a directory or a /**view** url
    #           rewrite (.*) /$1 last;
    #           break;
    #        }
    #       sendfile on;
    #   }
    # nginx.org/location-snippets: |
    #    sendfile off;
    #    # Required for Jenkins websocket agents
    #    proxy_set_header   Connection        $connection_upgrade;
    #    proxy_set_header   Upgrade           $http_upgrade;
    #    proxy_max_temp_file_size 0;
    #    client_body_buffer_size    128k;


spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.internal.locthp.com
    secretName: jenkins-certificate
  rules:
  - host: jenkins.internal.locthp.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jenkins-service
            port:
              number: 80