apiVersion: v1
kind: Secret
metadata:
    name: external-dns-tsig
    namespace: external-dns
type: Opaque
stringData:
    tsig-secret: ENC[AES256_GCM,data:m0XK7S56GbIre3U1f0E6iJ4jCaB7ZOIiuaCRn4Q1lIyR5W57UIfCta6lQwU=,iv:6KMCn4FY+QNAp6agxr6B73ICmRIj5xHNW88Qs0z2G5I=,tag:ylCtUyJ8ASXDOdVFDRPByg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdTJ5MllIQWI0cHJFNllM
            R0hyUEE3Y1VnMzd4Q0RUdDF4cXFKRjZ4QXlZCjBYTGpHNEJxS3hUVkZleXJodFBv
            SjEvVWdRdk15R1VaTDVaMThoVmJYYUUKLS0tIFBFMGJKNnJkRUIvUGV4OTAxUElP
            bXV5WlZaRTM2UVJObFFaWVhtcTkvUEEKLA/WaJ2RMucQAwYIs989k5h3supVoxg4
            5iACRI8ZzUDFgv8KEvn7tMw1uvSlcMSuIT6eEel/u1JxLdwdUUyvqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T07:19:34Z"
    mac: ENC[AES256_GCM,data:KkpjDKw0fEei1FEErW8NIlM0b/epnPe+j+NcgFRs7BkP6CiBWr6lluNBWHRsMX/r3QBe/unxe/mGuar+e/DrKMjf4dDPaHcKcjSjXd9oNeq8Wfark17TOOABtYY7PTS2FTWAPWoT/pNPaflrbxylT5dReqe0h03wxYBBzQcHqgE=,iv:LKBcbDAz7FoSFRaTg36YsMXhObV0CYELQkSeXtvh2Es=,tag:5nQnktKB6EQE9hpZaBU9eA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
