global:
  imagePullSecrets: []
image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: null
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: null
fullnameOverride: null
commonLabels: {}
serviceAccount:
  create: true
  labels: {}
  annotations: {}
  name: null
  automountServiceAccountToken: true
service:
  annotations: {}
  port: 7979
  ipFamilies: []
  ipFamilyPolicy: null
rbac:
  create: true
  additionalPermissions:
    - apiGroups:
        - traefik.io
        - traefik.containo.us
      resources:
        - ingressroutes
        - ingressroutetcps
        - ingressrouteudps
      verbs:
        - get
        - watch
        - list
deploymentAnnotations: {}
extraContainers: {}
deploymentStrategy:
  type: Recreate
revisionHistoryLimit: null
podLabels: {}
podAnnotations: {}
automountServiceAccountToken: true
shareProcessNamespace: false
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault
priorityClassName: null
terminationGracePeriodSeconds: null
dnsPolicy: null
dnsConfig: null
initContainers: []
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  capabilities:
    drop:
      - ALL
env:
  - name: RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: external-dns-tsig
        key: tsig-secret
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1
readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
extraVolumes: []
extraVolumeMounts: []
resources: {}
nodeSelector: {}
affinity: {}
topologySpreadConstraints: []
tolerations: []
serviceMonitor:
  enabled: false
  additionalLabels: {}
  annotations: {}
  namespace: null
  interval: null
  scrapeTimeout: null
  scheme: null
  tlsConfig: {}
  bearerTokenFile: null
  relabelings: []
  metricRelabelings: []
  targetLabels: []
logLevel: info
logFormat: text
interval: 1m
triggerLoopOnEvent: false
namespaced: false
sources:
  - service
  - ingress
  - traefik-proxy
policy: upsert-only
registry: txt
txtOwnerId: k8s-prod
txtPrefix: external-dns-
txtSuffix: null
domainFilters: []
excludeDomains: []
labelFilter: null
managedRecordTypes: []
provider:
  name: rfc2136
extraArgs:
  - --rfc2136-host=172.16.1.2
  - --rfc2136-min-ttl=300s
  - --rfc2136-port=53
  - --rfc2136-tsig-keyname=tsig-key
  - --rfc2136-tsig-secret=$(RFC2136_TSIG_SECRET)
  - --rfc2136-tsig-secret-alg=hmac-sha256
  - --rfc2136-zone=internal.locthp.com
  - --rfc2136-tsig-axfr
  - --traefik-disable-legacy
secretConfiguration:
  enabled: false
  mountPath: null
  subPath: null
  data: {}
enabled: null
