apiVersion: v1
kind: Secret
metadata:
    name: dashboard-auth-secret
    namespace: traefik
    labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/component: dashboard-auth
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Yu3NGWE=,iv:dSxiCeFdw/bKGRv0VBisHkCMkzmS8Fz0GOLHdV+0C7U=,tag:DH7bJ6H/LsqKbYH96/omGA==,type:str]
    password: ENC[AES256_GCM,data:ex6DZgNRVttQ2w==,iv:jqQSp7wxYj4UyoljIrku1sbBR78SvTJMDSVnQhUlOuM=,tag:K8cnC5Jwwd49LrE3vfuZeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTjBJM3prOEJqYmtSZ1Bx
            MGxMWllzb3pYdFpobDNsOWZORCtFdzZOQ1VRCndTQkh0bzlkS0dmc3lMTTkrb3lv
            UExCZjltc21aMUNidWlkdlltL0lZVHcKLS0tIEh2UHBOdzI3anRsUlBha000cjdH
            NmdUWWV2ZXdFT0ljRUZmeXNkdGJPZGcKlmwbd7NZSsu5spWA68opkGM1RLupjtmA
            uHzasxGmGy6+9jxi8apkWuhcmG3u8FInKWdQjdKyXWNYkUjsHBjelA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:03:45Z"
    mac: ENC[AES256_GCM,data:NVTw3cCoxK2mCUiPAiHA2LClqstQ60ga8Heyf7a/YVAo2JzKglbjNoyp0ActvmxsVUDGb5wnPeiLfMsAT4L9dib9McLmVIiXf/NraPzMGSlgIrh+vqVP2BYHGuyLBynjc2aAnUzQ7MJejfwDAt1FmGMHceLQIafgmmNUu/DuSB4=,iv:RdU8l1x8wGMwYgCk0DXN89YAyCGjB5ckcyTSfhZpUbk=,tag:bi/aAunKjtOH5R21SZx6AQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
