// Code generated by lister-gen. DO NOT EDIT.

package v1

// GlobalConfigurationListerExpansion allows custom methods to be added to
// GlobalConfigurationLister.
type GlobalConfigurationListerExpansion interface{}

// GlobalConfigurationNamespaceListerExpansion allows custom methods to be added to
// GlobalConfigurationNamespaceLister.
type GlobalConfigurationNamespaceListerExpansion interface{}

// PolicyListerExpansion allows custom methods to be added to
// PolicyLister.
type PolicyListerExpansion interface{}

// PolicyNamespaceListerExpansion allows custom methods to be added to
// PolicyNamespaceLister.
type PolicyNamespaceListerExpansion interface{}

// TransportServerListerExpansion allows custom methods to be added to
// TransportServerLister.
type TransportServerListerExpansion interface{}

// TransportServerNamespaceListerExpansion allows custom methods to be added to
// TransportServerNamespaceLister.
type TransportServerNamespaceListerExpansion interface{}

// VirtualServerListerExpansion allows custom methods to be added to
// VirtualServerLister.
type VirtualServerListerExpansion interface{}

// VirtualServerNamespaceListerExpansion allows custom methods to be added to
// VirtualServerNamespaceLister.
type VirtualServerNamespaceListerExpansion interface{}

// VirtualServerRouteListerExpansion allows custom methods to be added to
// VirtualServerRouteLister.
type VirtualServerRouteListerExpansion interface{}

// VirtualServerRouteNamespaceListerExpansion allows custom methods to be added to
// VirtualServerRouteNamespaceLister.
type VirtualServerRouteNamespaceListerExpansion interface{}
