// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned/typed/externaldns/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeExternaldnsV1 struct {
	*testing.Fake
}

func (c *FakeExternaldnsV1) DNSEndpoints(namespace string) v1.DNSEndpointInterface {
	return &FakeDNSEndpoints{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExternaldnsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
