apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:ZCCm8x6v3T5eXL7JCBqtDTOelpeecVBU9Yl03xHB5iyo7h3XVA==,iv:rV+8PnMQfLe/5V1sB5vvYp8OnlmSOEBI0dEKU3wMYys=,tag:EQ1/QObRyoXgNHYQNGzezQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZC9vbkR4VmloNU9zZjNx
            ZHIzUk5yd2UrVW02VElqL2pqVC9nWFhnZXhzCmFGUzFLMnhNQjdqdzZHQzRSZWpq
            MlV4dmdUMTk1WmlUdnNjZzBSNk9EdEEKLS0tIHNHWkh4UXFsSFd5NkZ3anl6bW4w
            VkNvbmZsYllmcFJZcUR0TGx1eTZvRUEKG3/3174eokVLepLUyMM+X3e39wBaKGXV
            lMXp4V48hr9I3Fqe2SbbKhE3CMaObxIWzlynooe10Nz3q5bId0JUUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T01:37:39Z"
    mac: ENC[AES256_GCM,data:heNvqxGd0/5oYCyy351jiSrCbhhSMXB7UmA/eOCRgyHROgU/8cdmbqCzwWQVfv4BecdVc6QEKbPiC6eOEhjJyXBqZkfqu31jH89vqnxkD4lX2IAlgRx7ZQdoc59L3jHHA7fxiAuzvc3CkPd3V6HSsYx36uBfVsGZWpeWbzBKzkw=,iv:6CKXnfKv6zqwXycybNOCmiPSeKMvbsa3S/4DRSuJXEE=,tag:U1yu15TChNCVxMLNwcpFog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
