apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - etcd-cert-syncer.yaml

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 82.16.2
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values.yaml

generators:
  - ./ksops.yaml