# Grafana admin credentials Secret
# The etcd-client-certs Secret is managed by the etcd-cert-syncer CronJob
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: grafana-creds
    namespace: observability
    labels:
        app.kubernetes.io/name: kube-prometheus-stack
        app.kubernetes.io/component: grafana
stringData:
    admin-user: ENC[AES256_GCM,data:88ecCMU=,iv:me1TeZCgcLqLg1kyXMULmFHhjp3dzgc1kkXGueYiTJg=,tag:BQMxUsc/Inn5aCQzp0sK5w==,type:str]
    admin-password: ENC[AES256_GCM,data:i9IJJa0FhhY3Wg==,iv:KRgDKjGq0vwVZ8COdN/qTbNDo6B+Yig2MHFSuCjmvdA=,tag:+tyL1uR68a4wXMkhttzV5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f2ga2qhdv6hpfhlelk7t633yzh78u4jdkwxkxrcpml5a7tzyd9ps99zmkj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVjFBNHZzS2wvTDdjZ3kr
            aHI4ZDVkY0pGcVFaZytUb0VjdUc4S2JjRzFJCi9WQkRLdGpLajBadGNSa2I5NzZn
            MUU0WEdxQVF0dmpJN2I4V01rL29LSkEKLS0tIDMzeEpNT3F1S1V6STVFeWNwK1dw
            NU55UURtNjY3VW9FdHZzTDRGYmlnTDAKDCOEJBKSkmGAFDRUPpUKUufQAkyL5N9D
            1AIga4Sv0wxoT7xBDBMCH6s9eUi+geidTGux9SEEaH3C9IympSb4BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T02:11:16Z"
    mac: ENC[AES256_GCM,data:DgowKoeGfKUBo/gu9/nd6eX6WfA3yD/h0WkKpovz+azHPgFTv9k6U65dQMINTaiLThvVnZdHVglmIEsANdqoHSpMgFPnnlUeS1/fvyOb6RhxK11lwDUebWCM/ui+4FBAV2WRYbgEz/vEwsqNToSNVy+8GNLn4rzWGEAvMlL5GXc=,iv:RC1CwLpesn2izrdaB60H2JYzLJUl6sicOSiZEa4SJBE=,tag:V24Pw4AQiLTEFiTW7PdgvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
