version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
    networks:
      - monitoring
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    container_name: alertmgr
    networks:
      - monitoring
    ports:
      - "9093:9093"
    configs:
      - source: alertmanager_config
        target: /config/alertmanager.yml
    command: --config.file=/config/alertmanager.yml --log.level=debug
networks:
  monitoring:
    driver: bridge
configs:
  alertmanager_config:
    content: |
      route:
        receiver: 'Mail Alert'
        group_by: [ alertname, instance, device ]
        repeat_interval: 30s
        group_wait: 15s
        group_interval: 15s

      receivers:
        - name: 'Mail Alert'
          email_configs:
            - smarthost: $ALERTMANAGER_SMTP_SMTP_SERVER:$ALERTMANAGER_SMTP_SMTP_PORT
              auth_username: $ALERTMANAGER_SMTP_SMTP_USERNAME
              auth_password: $ALERTMANAGER_SMTP_SMTP_PASSWORD
              from: $ALERTMANAGER_SMTP_SMTP_FROM
              to: $ALERTMANAGER_SMTP_SMTP_TO
              headers:
                subject: 'Prometheus Mail Alerts'
