version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
       - ./grafana/provisioning/:/etc/grafana/provisioning/datasources/
       - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      # Configs files
      - ./prometheus/:/etc/prometheus/
      # Volume to persist data across recreation
      - prometheus_data:/prometheus
    networks:
      - monitoring
    #command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    command: [ "--web.enable-lifecycle", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles"]
  alertmanager:
    image: prom/alertmanager:latest
    restart: unless-stopped
    container_name: alertmgr
    networks:
      - monitoring
    ports:
      - "9093:9093"
    configs:
      - source: alertmanager_config
        target: /config/alertmanager.yml
    command: --config.file=/config/alertmanager.yml --log.level=debug
volumes:
  prometheus_data:
  grafana_data:
networks:
  monitoring:
    driver: bridge
configs:
  alertmanager_config:
    content: |
      route:
        receiver: 'Mail Alert'
        group_by: [ alertname, instance, device ]
        repeat_interval: 30s
        group_wait: 15s
        group_interval: 15s
      
      receivers:
        - name: 'Mail Alert'
          email_configs:
            - smarthost: $ALERTMANAGER_SMTP_SMTP_SERVER:$ALERTMANAGER_SMTP_SMTP_PORT
              auth_username: $ALERTMANAGER_SMTP_SMTP_USERNAME
              auth_password: $ALERTMANAGER_SMTP_SMTP_PASSWORD
              from: $ALERTMANAGER_SMTP_SMTP_FROM
              to: $ALERTMANAGER_SMTP_SMTP_TO
              headers:
                subject: 'Prometheus Mail Alerts'




